application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "zero2prod"
  require_ssl: false
email_client:
  base_url: "postmark.com"
  sender: "test@gmail.com"
  timeout_milliseconds: 10000
